### PR TITLE
chore: bump formkit version to 0.18.0

### LINKED ISSUE #4424: 升级 Formkit 版本之后，系统初始化时输入框报错
### 是什么版本出现了此问题？

2.9.0-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

_No response_

### 发生了什么？

系统初始化时，输入用户名则会出现如下错误：

image

进而导致无法点击初始化按钮。其他输入框未出现此问题
经过测试，与 Formkit 版本升级有关 #4411 

/kind bug

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/area console
/kind bug
/milestone 2.9.x

#### What this PR does / why we need it:

升级 FormKit 依赖至 [0.18.0](https://formkit.com/changelog#_0180-beta-18)

修复[升级到 0.17.5](https://github.com/halo-dev/halo/pull/4411) 之后输入框失去焦点之后无法提交的问题。

see https://github.com/halo-dev/halo/issues/4424#issuecomment-1677331547

#### Which issue(s) this PR fixes:

Fixes #4424 

#### Special notes for your reviewer:

需要测试各个输入框是否正常工作。

#### Does this PR introduce a user-facing change?

```release-note
升级 FormKit 的依赖至 0.18.0
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/hold

需要等待 https://github.com/halo-dev/halo/pull/4427 合并。FormKit 0.18.0 需要依赖 Vue 3.3 才能正常工作。

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
