### PR TITLE
chore: cleanup deprecated class

### PR DESCRIPTION
**Pull request by guqing**
### What this PR does?
删除被废弃的类和相关测试

/kind cleanup
/cc @halo-dev/sig-halo

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
/lgtm
/hold

**Review by JohnNiang — COMMENTED** [review]
/lgtm
/unhold

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by guqing** [comment]
需要一个 approve

**Pull request merged**
