### PR TITLE
Upgrade Lucene to 9.5.0

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind improvement
/area core
/milestone 2.2.x

#### What this PR does / why we need it:

See https://lucene.apache.org/core/9_5_0/MIGRATE.html for more.

#### Special notes for your reviewer:

Please confirm that the search widget is working fine.

#### Does this PR introduce a user-facing change?

```release-note
升级依赖 Lucene 至 9.5.0
```

### CODE REVIEW

**Comment by ruibaby** [comment]
image
image

搜索和重建索引似乎都有问题。

**Comment by guqing** [comment]
我没有复现
启动前 clean 过排除干扰
image
image

**Comment by JohnNiang** [comment]
@ruibaby ，你遇到的问题我也遇到了。不过目前能想到的临时解决方案：
1.  重建索引
2.  删除掉旧的 indices 文件

**Comment by ruibaby** [comment]
> @ruibaby ，你遇到的问题我也遇到了。不过目前能想到的临时解决方案：
> 
> 1. 重建索引
> 2. 删除掉旧的 indices 文件

升级 Halo 的时候怎么办呢，应该是已经有 indices 文件的。

**Comment by JohnNiang** [comment]
/hold

尝试解决兼容性问题。

**Comment by JohnNiang** [comment]
/unhold

I've added lucene-backward-codecs to avoid search failure after upgrading. Please help us test it again. @halo-dev/sig-halo

**Review by ruibaby — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
