### PR TITLE
feat: add support for selecting the parent category when creating a new category

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/area console
/kind feature
/milestone 2.7.x

#### What this PR does / why we need it:

支持在创建分类的时候选择上级分类。

image

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/4040

#### Special notes for your reviewer:

测试方式：

1. 测试新建的时候指定上级分类的功能是否正常。
2. 点击某个分类的操作按钮，选择添加子分类的菜单项，检查在新建分类的表单中上级分类是否选中了此分类。

#### Does this PR introduce a user-facing change?

```release-note
Console 端的文章分类支持在新建时指定上级分类。
```

### CODE REVIEW

**Comment by ruibaby** [comment]
cc @halo-dev/sig-halo

**Review by guqing — APPROVED** [review]
/approve

**Comment by ruibaby** [comment]
@halo-dev/sig-halo-console cc

**Pull request merged**
