### PR TITLE
refactor: optimize notification and subscription query using index

### PR DESCRIPTION
**Pull request by guqing**
### What type of PR is this?
/kind improvement
/area core
/milestone 2.13.x

### What this PR does / why we need it:
使用索引机制优化通知和订阅查询以提高性能

how to test it
测试通知列表不报错即可

### Does this PR introduce a user-facing change?

```release-note
使用索引机制优化通知和订阅查询以提高性能
```

### CODE REVIEW

**Comment by guqing** [comment]
/ping @ruibaby 通知查询的参数有变动需要重新生成 api-client 并配置,将查询字段都改为对应的 spec.xxx

**Comment by ruibaby** [comment]
> /ping @ruibaby 通知查询的参数有变动需要重新生成 api-client 并配置,将查询字段都改为对应的 spec.xxx

Done

**Review by JohnNiang — APPROVED** [review]
It works very well.

/approve

**Review by ruibaby — APPROVED** [review]
/lgtm

**Pull request merged**
