### PR TITLE
Replace webmvc with webflux

### LINKED ISSUE #2109: Integrate WebFlux instead of Servlet
### Your current Halo version

2.0.0-SNAPSHOT

#### Why we need WebFlux?

Please refer to:
- https://www.infoq.com/articles/Servlet-and-Reactive-Stacks-Spring-Framework-5/
- https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-ann-requestmapping-composed
- https://docs.spring.io/spring-boot/docs/3.0.0-M3/reference/htmlsingle/#web.reactive
- https://docs.spring.io/spring-security/reference/6.0.0-M3/reactive/index.html

### Additional information

/kind improvement
/area core

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind cleanup
/kind optimization

#### What this PR does / why we need it:

1. Replace webmvc with webflux
2. Simplify JWT authentication procedure
3. Refine Swagger API documents
4. Remove unused controllers
5. Refactor security configuration entirely

#### Which issue(s) this PR fixes:

Fixes #2109 

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo 
/area core
/milestone 2.0

Hi @halo-dev/sig-halo , you might notice that the personal access token authentication module gone, please don't feel surprised. I will refactor it after this PR is merged.

##### How to test it?

1. Authenticate with form login
    * Run Halo application
    * Open your browser and request <http://localhost:8090>
    * You will be redirected from `/` to `/login` page
    * Input username and password (for test: user/password)
    * See the default 404 page `Whitelabel Error Page`
3. Authenticate with token API
    
    * Login using cURL command
        ```bash
        curl -X POST --location "http://localhost:8090/api/auth/token" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{
                \"username\": \"user\",
                \"password\": \"password\"
                }"
        ```
    * Access a resource API by using the token obtained from login
        ```bash
        curl -X GET --location "http://localhost:8090/apis/fake.halo.run/v1/posts" \
            -H "Authorization: Bearer replace_with_your_token"
        ```
    * You will get a 403 Forbidden error due to insufficient_scope

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve

**Comment by guqing** [comment]
TODO: 
- Persist JWT
- You can only get a token once when you use a token to get it again, and the current token can no longer be used after you get it again

**Review by ruibaby — COMMENTED** [review]
/approve

**Pull request merged**
