### PR TITLE
fix: The initial value of birthday in PrimaryProperties file is 0，The construction time of the website is 19053.

### PR DESCRIPTION
**Pull request by lan-yonghui**
The initial value of birthday in PrimaryProperties file is 0, The construction time of the website is 19053.

### CODE REVIEW

**Comment by guqing** [comment]
hi @lan-yonghui 请先修复CI以确保其能运行通过✅

**Comment by lan-yonghui** [comment]
> hi @lan-yonghui 请先修复CI以确保其能运行通过✅

好哒

**Review by guqing — APPROVED** [review]

**Review by ruibaby — APPROVED** [review]

**Review by JohnNiang — APPROVED** [review]
LGTM

**Comment by JohnNiang** [comment]
Fix #1696

**Pull request merged**
