### PR TITLE
fix: single page does not count visits

### LINKED ISSUE #2912: 发现后台配置得自定义页面，不会统计阅读量
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

_No response_

### 发生了什么？

后台配置自定义页面，比如“关于”页面，前台阅读访问之后，并未统计阅读量

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind bug
/area core

#### What this PR does / why we need it:
修复自定义页面没有统计访问量的问题
#### Which issue(s) this PR fixes:

Fixes #2912

#### Special notes for your reviewer:
how to test it?
创建自定义页面并到主题端访问，可以看到访问量增加

/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?
```release-note
修复自定义页面没有统计访问量的问题
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

image

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
