### PR TITLE
Fix the problem of being able to search deleted posts

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind bug
/kind improvement
/area core

#### What this PR does / why we need it:

This PR refactors post reconciler to reduce post updates and refines post events.

Previously, we need 3 - 4 updates per reconciliation, but now we only need 1. And all events collected in reconciler will be fired after updating post.

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3121

#### Special notes for your reviewer:

0. Install search plugin
1. Create a public post and publish it
2. Search posts
3. Try to make the post private
4. Search posts
5. Try to make the post public
6. Search posts
7. Try to delete the post
8. Search posts
9. Try to recover the post
10. Search posts

#### Does this PR introduce a user-facing change?

```release-note
修复依然能搜索到已删除文章的问题
```

### CODE REVIEW

**Comment by LIlGG** [comment]
目前自定义摘要变更时，索引不会更新。这块是否需要考虑到？如果是自动生成的摘要，则会跟随文章发布更新索引。

**Comment by JohnNiang** [comment]
> 目前自定义摘要变更时，索引不会更新。这块是否需要考虑到？如果是自动生成的摘要，则会跟随文章发布更新索引。

Good catch! 

/hold

**Review by LIlGG — APPROVED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
