### PR TITLE
chore: move the ExtensionVoOperator to the api directory so that the plugin can implement the interface

### PR DESCRIPTION
**Pull request by Roozenlz**
#### What type of PR is this?
/kind improvement

#### What this PR does / why we need it:
插件中的VO类目前无法实现接口run.halo.app.theme.finders.vo.ExtensionVoOperator，因为插件的依赖中不存在该接口，导致主题中使用形如`#annotations.get(extension,key)`的语法报错

#### Which issue(s) this PR fixes:

Fixes （https://github.com/halo-sigs/plugin-links/issues/42）

#### Special notes for your reviewer:
希望更新一下api的依赖包
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
/approve

Thanks for your first contribution!

**Review by ruibaby — COMMENTED** [review]
/lgtm

Nice Work!

**Comment by ruibaby** [comment]
@Roozenlz 合并之前，需要先签署一下我们的 CLA：https://github.com/halo-dev/halo/pull/4356#issuecomment-1661487677

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
