### PR TITLE
Add Pull Request template

### LINKED ISSUE #1718: 提供 Pull Request 模板
### 你当前使用的版本

1.5.0-alpha.2

### 描述一下此特性

RT，需要在里面描述一下内容：

1. 这个 PR 做了什么。
2. 如何测试这个改动。
3. 对应的 issue。
4. 提示需要编写单元测试。
5. ...

/cc @halo-dev/sig-halo 

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Add Pull Request template for release note.

We have decided to use `release-note` plugin, see https://github.com/halo-dev/test-infra/pull/21 for more.

About release-note, please refer to: 
- https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md
- https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-notes

#### Which issue(s) this PR fixes:

Fixes #1718

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
