### PR TITLE
feat: allow users to manage their attachments in uc

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind feature
/milestone 2.20.x
/area core

#### What this PR does / why we need it:
支持用户在个人中心管理自己的附件（需要具有对应权限）

Fixes https://github.com/halo-dev/halo/issues/5278

#### Does this PR introduce a user-facing change?
```release-note
支持用户在个人中心管理自己的附件（需要具有对应权限）
```

### CODE REVIEW

**Comment by guqing** [comment]
@ruibaby 帮忙适配一下 UC

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by LIlGG — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
