### PR TITLE
fix: outline not displayed when first entering the editor.

### LINKED ISSUE #3769: 打开之前写过的文章，在大纲中没有目录，需要在文章任意地方敲回车以后才会出现
### 是什么版本出现了此问题？

 2.4.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

_No response_

### 发生了什么？

打开之前写过的文章，在大纲中没有目录，需要在文章任意地方敲回车以后才会出现

### 相关日志输出

_No response_

### 附加信息

https://user-images.githubusercontent.com/102512051/232656070-769a5b82-4094-4e50-a968-2bbadc8609e1.mp4

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?
/kind bug
/area console

#### What this PR does / why we need it:
为默认编辑器侦听器增加 `immediate` 属性，使其在创建之后立即执行，生成目录。

#### Which issue(s) this PR fixes:
Fixes #3769 

#### Special notes for your reviewer:
打开已经存在并且具有标题的文章/页面，查看大纲是否正常生成。

#### Does this PR introduce a user-facing change?
```release-note
修复文章/页面已有内容重新编辑时，无法立即显示大纲的问题。
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
