### PR TITLE
chore: async api client

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement
/area console

#### What this PR does / why we need it:

同步 api client。

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
/hold

等待 https://github.com/halo-dev/halo/issues/3944 完成。

**Review by LIlGG — APPROVED** [review]
/lgtm

**Pull request merged**
