### PR TITLE
fix: the keyword and categoryId parameters of the post list api are required #1432

### LINKED ISSUE #1432: 1.4.10 API更新导致WeHalo小程序无法获取文章列表
### 是什么版本出现了此问题？

1.4.10

### 使用的什么数据库？

H2

### 在线站点地址

https://m.xiaobaipb.com

### 发生了什么？

更新：Content Api 中的获取文章列表支持传入关键字和分类 id 筛选项。halo-dev/halo#1373
问题：1.4.10 API 更新导致 WeHalo 小程序无法获取文章列表，需要新增关键字和分类 id 参数才能正常访问。

### 相关日志输出

```shell
org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'keyword' for method parameter type String is not present
org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'categoryId' for method parameter type String is not present
```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by ruibaby**
Close #1432

### CODE REVIEW

**Comment by JohnNiang** [comment]
Please rename your PR title.

**Review by guqing — APPROVED** [review]

**Comment by JohnNiang** [comment]
Hi @ruibaby , have you test this API manually?

**Comment by ruibaby** [comment]
> Hi @ruibaby , have you test this API manually?

yes

**Comment by JohnNiang** [comment]
OK, thanks for your time.

/lgtm

**Pull request merged**
