### PR TITLE
chore: bump uppy related packages version

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/area console
/kind improvement
/milestone 2.12.x

#### What this PR does / why we need it:

升级 Uppy 相关的依赖。

https://github.com/transloadit/uppy/releases/tag/uppy%403.21.0

#### Special notes for your reviewer:

测试附件上传组件功能是否正常即可。

#### Does this PR introduce a user-facing change?

```release-note
升级 Uppy 相关的依赖。

```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Please fix the failing checks first.

**Comment by ruibaby** [comment]
> Please fix the failing checks first.

Done

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
