### PR TITLE
test: add e2e testing for the backend

### PR DESCRIPTION
**Pull request by LinuxSuRen**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:
It would keep the important APIs always works well.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
I just added parts of the APIs. But the most imporant part is making the e2e testing flow works well. Please let me kown if you believe there some other core APIs need e2e testing as well. I can do it in this PR or create a new one for that. No matter what. thanks for your time to review it.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
Halo is long-term lack of E2E test. Thank you for resolving this issue.

/approve
/ping @halo-dev/sig-halo

**Review by ruibaby — APPROVED** [review]
/approve

Thanks for your contribution~

**Comment by LinuxSuRen** [comment]
I'd happy to make two projects be better. Please let me know if there are some crucial APIs that need the e2e, or make the e2e flow be much simpler.

**Review by guqing — COMMENTED** [review]
/lgtm

Thanks for your contribution♥️

**Comment by JohnNiang** [comment]
I'm going to merge this PR manually due to the inability of Prow to automatically merge.

image

**Comment by LinuxSuRen** [comment]
There is an error of the image tag handling. I'm trying to fix it.

**Pull request merged**
