### PR TITLE
Add support for restoring from backup root

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/area core
/area console

#### What this PR does / why we need it:

This PR adds support of restoring from backup root.

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/6370

#### Does this PR introduce a user-facing change?

```release-note
支持从备份目录选择文件进行恢复
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @halo-dev/sig-halo-console , please help me adapt the console to support restoring Halo from backup root.

**Comment by ruibaby** [comment]
> Hi @halo-dev/sig-halo-console , please help me adapt the console to support restoring Halo from backup root.

vme50，and then live-stream teaching you console adaptation

**Comment by JohnNiang** [comment]
Hi @ruibaby , 选择备份文件进行恢复时，没有提示选择的具体备份文件

image

**Comment by ruibaby** [comment]
/retitle Add support of restoring from backup root

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — APPROVED** [review]
/approve

**Pull request merged**
