### PR TITLE
feat: hide registration-related options when allowRegistration is disabled

### LINKED ISSUE #5688: 为用户设置中的 默认角色 设置默认值 或改为必填
### 你当前使用的版本

2.14.0

### 描述一下此特性

/area core

如图，现有行为允许此选项为 `请选择角色`，值为 `"defaultRole": ""`
但此时可以保存成功，注册选项也在ui显示，但无法注册，这种现象是在预期内的吗

image
image
image

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by mashirot**
#### What type of PR is this?

/kind improvement
/area core

#### Which issue(s) this PR fixes:

Fixes #5688 

```release-note
当未开启允许注册选项时，隐藏注册相关的其他选项。
```

### CODE REVIEW

**Comment by mashirot** [comment]
> 我感觉这个选项似乎也可以隐藏呢，要不要在这个 PR 上一并处理了。

🆗

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by LIlGG — APPROVED** [review]
Thanks for your contribution!

/lgtm

**Review by guqing — APPROVED** [review]
/approve

**Pull request merged**
