### PR TITLE
Allow configuration of external access url

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:

Many permanent links will be generated in the system, in order to ensure accessiblity, we will allow users to configure external access links instead of internal url.

#### Special notes for your reviewer:

Before starting the application, we need to modify the following configuration into the configuration file(application.yaml):

```yaml
halo:
  external-url: https://halo.run
```

Then, after booting the application, check for permalinks of attachments.

#### Does this PR introduce a user-facing change?

```release-note
支持在配置文件中修改博客访问链接
```

### CODE REVIEW

**Comment by ruibaby** [comment]
文章、分类、标签的 permalink 目前是没有带域名的，需要在这个 PR 一起修改吗？

**Comment by guqing** [comment]
> 文章、分类、标签的 permalink 目前是没有带域名的，需要在这个 PR 一起修改吗？
 
如果将 permalink 带上域名，注册到 RouterFunction 的时候不好处理哦

**Comment by JohnNiang** [comment]
> 

目前还有不少相关的 PR 正在进行中，为避免冲突，暂时不修改其他地方。

**Review by guqing — COMMENTED** [review]
/approve

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
