### PR TITLE
Support filtering and sorting plugins

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:

Support filtering and sorting plugins. e.g.:

```bash
http://localhost:8090/api/api.console.halo.run/v1alpha1/plugins?keyword=xyz&enabled=true&sort=creationTimestamp,desc
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2470

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by guqing** [comment]
@JohnNiang  修复一下测试用例

**Comment by JohnNiang** [comment]
/hold

image

**Review by ruibaby — COMMENTED** [review]
/approve

实际测试符合预期。

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
