### PR TITLE
Fix the problem that it is always in deleting phase after deleting backups

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind bug
/area core
/milestone 2.9.x

#### What this PR does / why we need it:

Before this, if we deleted a backup without filename, the BackupReconciler would get stuck infinitely. And no further backups would be reconciled.

This PR fixes the problem that it is always in deleting phase after deleting backups.

#### Does this PR introduce a user-facing change?

```release-note
修复因备份数据状态不正常导致无法正常删除备份的问题。
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by GodlessLiu** [comment]
Running well! ! 但是有个问题，为什么当我进行备份之后，使用当前备份进行恢复。恢复成功之后这个备份记录会被标记为失败的。
image
image

**Review by guqing — APPROVED** [review]
/approve

**Comment by JohnNiang** [comment]
I have confirmed that the problem was introduced by <https://github.com/halo-dev/halo/pull/4391>. So we don't need to cherry pick the PR into release-2.8.

**Comment by JohnNiang** [comment]
> Running well! ! 但是有个问题，为什么当我进行备份之后，使用当前备份进行恢复。恢复成功之后这个备份记录会被标记为失败的。 image image

Hi @GodlessLiu ，关于恢复成功后备份记录标记为失败的问题，我将提交新的 PR 来修复它。

**Pull request merged**
