### PR TITLE
chore: bump tiptap version to 2.3.0

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/area ui
/kind improvement

#### What this PR does / why we need it:

升级 Tiptap 的版本为 2.3.0。

- https://github.com/ueberdosis/tiptap/releases/tag/v2.3.0
- https://github.com/ueberdosis/tiptap/releases/tag/v2.2.6
- https://github.com/ueberdosis/tiptap/releases/tag/v2.2.5
- https://github.com/ueberdosis/tiptap/releases/tag/v2.2.4

#### Does this PR introduce a user-facing change?

```release-note
升级 Tiptap 的版本为 2.3.0。
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — COMMENTED** [review]
[2.3.0](https://github.com/ueberdosis/tiptap/releases/tag/v2.3.0) 已经发布了，是否需要升级呢？

**Comment by ruibaby** [comment]
> [2.3.0](https://github.com/ueberdosis/tiptap/releases/tag/v2.3.0) 已经发布了，是否需要升级呢？

等当前其他编辑器相关的 PR 合并之后再改。

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
