### PR TITLE
Allow E2E testing to fail

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind cleanup
/area core
/milestone 2.18.x

#### What this PR does / why we need it:

This PR allows E2E testing to fail due to frequently failing E2E testing.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/lgtm

**Review by LIlGG — APPROVED** [review]
/lgtm

**Review by guqing — APPROVED** [review]
/lgtm

**Pull request merged**
