### PR TITLE
Support restarting Halo

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/area core
/milestone 2.9.x

#### What this PR does / why we need it:

Support restarting Halo and enable restart endpoint by default.

Restart endpoint detail:

request uri: `/actuator/restart`
request method: `POST`

Please note that memory usage may slightly increase after restarting Halo.

#### Does this PR introduce a user-facing change?

```release-note
支持在线重启 Halo。
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @ruibaby ，可能需要同步修改一下恢复页面和确认框的文案。

**Comment by ruibaby** [comment]
> Hi @ruibaby ，可能需要同步修改一下恢复页面和确认框的文案。

Done

**Comment by ruibaby** [comment]
@halo-dev/sig-halo 建议好好测一下这个 PR。

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — APPROVED** [review]
/approve

**Pull request merged**
