### PR TITLE
fix: error occurred when switching tab in dashboard component.

### LINKED ISSUE #3764: 仪表盘添加组件浏览器控制台报错
### 是什么版本出现了此问题？

v2.4.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

_No response_

### 发生了什么？

仪表盘添加组件时，切换组件类型标签页控制台报错。
image

image

```
2c3.js:1  DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insert (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:61208)
    at g (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:42680)
    at h (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:42313)
    at L (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:51483)
    at I (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:49933)
    at A (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:45223)
    at h (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:42372)
    at L (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:50363)
    at I (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:49933)
    at A (http://localhost:8090/console/assets/vue/vue.global.fe0fe2c3.js:1:45223)
(匿名) @ vue.global.fe0fe2c3.js:1
```

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?
/kind bug
/area console

#### What this PR does / why we need it:
修复 Console 端仪表盘添加组件时，切换标签页面报错的问题。

#### Which issue(s) this PR fixes:
Fixes #3764 

#### Does this PR introduce a user-facing change?
```release-note
修复 Console 端仪表盘添加组件时的报错问题。
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/approve

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
