### PR TITLE
fix: the e2e script exit code handling is incorrect

### PR DESCRIPTION
**Pull request by LinuxSuRen**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/6096

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Sometimes, it will have the following errors. @JohnNiang do you have any ideas about it?

```shell
testing-1  | start to send request to http://halo:8090/apis/api.console.halo.run/v1alpha1/users/bnmJqS/password
testing-1  | test case "updateUserPass", status code: 500
testing-1  | response body: {"type":"about:blank","title":"Internal Server Error","status":500,"detail":"Something went wrong, please try again later.","instance":"http://halo:8090/apis/api.console.halo.run/v1alpha1/users/bnmJqS/password","requestId":"f3fea404-10","timestamp":"2024-06-21T01:49:03.746356448Z"}
```

**Comment by JohnNiang** [comment]
Hi @LinuxSuRen , sorry for the delayed reply.

Recently, I'm developing Halo 2.17. After releasing 2.17, I will try to fix the e2e test with you.

**Comment by JohnNiang** [comment]
Hi @LinuxSuRen , current checks have been passed.

After my investigation, I found the following error:

```java
2024-07-02T19:02:01.283+08:00 ERROR 7 --- [reactor-tcp-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [811a9304-10]  500 Server Error for HTTP PUT "/apis/api.console.halo.run/v1alpha1/users/CWVwjs/password"

org.springframework.dao.OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/users/CWVwjs]
	at org.springframework.data.r2dbc.core.R2dbcEntityTemplate.lambda$doUpdate$12(R2dbcEntityTemplate.java:638) ~[spring-data-r2dbc-3.3.1.jar:3.3.1]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
``` 

The problem of `updateUserPass` case is caused by optimistic locking error, which do not always occurred. It would be better if the case runs could be retried conditionally.

/lgtm
/approve

**Comment by LinuxSuRen** [comment]
> It would be better if the case runs could be retried conditionally.

In this case, the test case just found a bug. IMO, it should return if any errors exist.

**Comment by JohnNiang** [comment]
> > It would be better if the case runs could be retried conditionally.
> 
> In this case, the test case just found a bug. IMO, it should return if any errors exist.

In fact, the optimistic locking error is not a bug in Halo, see https://github.com/halo-dev/halo/issues/6254 for more. If we encounter the error, retry strategy is needed.

**Pull request merged**
