### PR TITLE
feat: add encryption setting for email notifier

### LINKED ISSUE #4674: 期望邮件通知支持SSL
### 你当前使用的版本

2.10.0-alpha.1

### 描述一下此特性

目前邮件通知似乎还没有支持SSL协议

期望可选使用SSL/TLS 安全发送或接收电子邮件

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind improvement
/area core
/milestone 2.10.x

#### What this PR does / why we need it:
为邮件通知发件设置增加加密方式配置

#### Which issue(s) this PR fixes:
Fixes #4674

#### Does this PR introduce a user-facing change?
```release-note
为邮件通知发件设置增加加密方式配置
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/hold

等待 https://github.com/halo-dev/halo/pull/4685 合并。

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Review by ruibaby — COMMENTED** [review]
/lgtm
/unhold

**Pull request merged**
