### PR TITLE
fix: issue of post details page without meta_description variables

### LINKED ISSUE #2281: 文章页面的 meta_description 变量为空
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://ryanc.cc

### 发生了什么？

在正常情况下，如果文章设置中没有设置自定义描述，那么会在请求文章页面的时候根据文章内容生成 meta_description 内容。但当前不符合预期。

例如：

https://ryanc.cc/archives/halo-150-released.html

相关代码逻辑位置：https://github.com/halo-dev/halo/blob/68d263bef3d5ae61e57ba2e9508a9eeda12c3d29/src/main/java/run/halo/app/controller/content/model/PostModel.java#L147-L152

/kind bug
/milestone 1.5.x

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind bug
/area core
/milestone 1.5.x

#### What this PR does / why we need it:
修复文章内容查询问题导致 meta_description 内容生成为空
#### Which issue(s) this PR fixes:

Fixes #2281 

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
修复文章内容查询问题导致的文章详情页 meta_description 为空 
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/retitle fix: issue of post details page without meta_description variables

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
