### PR TITLE
Prepare for developing Halo 2.8.1

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind cleanup
/area core

#### What this PR does / why we need it:

Bump up Halo to `2.8.1` for developing Halo 2.8.1.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
/hold

需要同步修改 GitHub workflow。

**Review by guqing — APPROVED** [review]
/approve

**Comment by JohnNiang** [comment]
> /hold
> 
> 需要同步修改 GitHub workflow。

/unhold

See https://github.com/halo-dev/halo/pull/4345/commits/79467475113ac2e1accf30929e7a73c82225957c for more.

**Review by ruibaby — APPROVED** [review]
/lgtm

**Pull request merged**
