### PR TITLE
fix typo: swagger api operation title typo

### PR DESCRIPTION
**Pull request by ikvarxt**
修复 Admin API 中 post-controller 永久删除 Post 操作名称拼写错误。

https://api.halo.run/admin-api.html#operation/deletePermanentlyUsingDELETE_6

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by guqing** [comment]
thank you for your first contribution 🥳

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
