### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by JohnNiang**
- Update spring boot version to 2.4.0
- Update source compatibility version to 11
- Update swagger version to 3.0.0

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]

**Comment by lnsane** [comment]
> * Update spring boot version to 2.4.0
> * Update source compatibility version to 11
> * Update swagger version to 3.0.0

为什么升级Java版本出于什么考虑

**Comment by ruibaby** [comment]
> > * Update spring boot version to 2.4.0
> 
> > * Update source compatibility version to 11
> 
> > * Update swagger version to 3.0.0
> 
> 
> 
> 为什么升级Java版本出于什么考虑

https://bbs.halo.run/d/1208-jdk811/8

**Comment by lnsane** [comment]
@ruibaby  谢谢

**Comment by JohnNiang** [comment]
> > * Update spring boot version to 2.4.0
> > * Update source compatibility version to 11
> > * Update swagger version to 3.0.0
> 
> 为什么升级Java版本出于什么考虑

在 1.4.x 上升级至 Java 11 确实不太合适，造成了 Break Change。后续升级的时候会注意到这个问题。

**Pull request merged**
