### PR TITLE
feat: add a default annotation setting for menu item

### LINKED ISSUE #2878: 希望halo2可以在新加菜单表单里加入菜单图标表单
### 你当前使用的版本

halo2.0

### 描述一下此特性

halo2.0新加菜单里没用菜单图标的输入框

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind feature
/milestone 2.1.x
/area core
#### What this PR does / why we need it:
为菜单项新增图标元数据扩展

#### Which issue(s) this PR fixes:

Fixes #2878

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?
```release-note
为菜单添加图标元数据扩展
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by JohnNiang — CHANGES_REQUESTED** [review]
文件名建议：`annotationsettings-menuitem.yaml`

**Comment by ruibaby** [comment]
仔细思考了一下，图标还是交给主题开发来定义 AnnotationSetting 实现吧，考虑到以下几点：

1. 不是所有主题对此有需求。
2. 每个主题的图标方案不一致。

https://github.com/halo-dev/halo/issues/2878#issuecomment-1366422903

**Pull request closed without merging**
