### PR TITLE
Use task list for issue and pr checks

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR use task list for issue and pr checks.

See https://github.com/orgs/halo-dev/discussions/7001 for more.

#### Which issue(s) this PR fixes:

Fixes https://github.com/orgs/halo-dev/discussions/7001

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
这样改本质上还是 Markdown 内容，不能阻止表单提交，可以考虑直接用 checkboxes，参考：https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by JohnNiang** [comment]
Please test from <https://github.com/JohnNiang/halo/issues/new/choose>.

**Review by ruibaby — APPROVED** [review]
VERY GOOD, MAKE HALO GREAT AGAIN.

/lgtm

image

**Pull request merged**
