### PR TITLE
feat: support configuring notifier for different notification reason types

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind feature
/area core
/area console
/milestone 2.10.x

#### What this PR does / why we need it:

用户支持为不同的通知事件配置通知方式

image

#### Does this PR introduce a user-facing change?

```release-note
用户支持为不同的通知事件配置通知方式
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/hold 

等待 https://github.com/halo-dev/halo/pull/4688 合并，然后给开关加上加载状态。

**Review by ruibaby — COMMENTED** [review]
/lgtm

功能符合预期

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
