### PR TITLE
fix: searching posts without related contents

### LINKED ISSUE #1842: 文章搜索时关联内容进行搜索
### Checklist

- [X] The issue has been searched in [GitHub Issues](https://github.com/halo-dev/halo/issues)
- [X] The issue has been searched in the [bbs.halo.run](https://bbs.halo.run/)
- [X] Already consulted [document](https://docs.halo.run/)

### What is version of Halo has the issue?

1.5.2

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

拆分了内容表后，文章搜索没有同步修改内容搜索字段，导致根据关键字搜索文章内容失效
需要修改如下代码关联到 contents 表查询内容
https://github.com/halo-dev/halo/blob/63e8cd0cd53b92c3571981bcb81454f23b8ae34a/src/main/java/run/halo/app/service/impl/PostServiceImpl.java#L574

### PR DESCRIPTION
**Pull request by Yhcrown**
### What this PR does?
fix #1842 
现在查询的时候会关联content表。

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

经过测试，符合预期。

**Comment by ruibaby** [comment]
/retitle fix: searching posts without related contents

**Review by JohnNiang — COMMENTED** [review]
/approve

**Pull request merged**
