### PR TITLE
feat: add more role templates

### LINKED ISSUE #2342: 完善默认初始化的系统角色
### 你当前使用的版本

next

### 描述一下此特性

完善默认初始化的系统角色，当前只有 super-role（超级管理员），期望有以下角色。

1. 超级管理员，包含所有权限。
2. 管理员，包含一般的管理权限。无某些涉及到系统核心的权限（如：插件停止和卸载等）。
3. 编辑，包含对内容模块资源的创建权限。
4. 访客，仅包含对个人账号的管理权限。

需要注意的是，系统初始化的系统角色不允许修改和删除，但可以基于以上权限创建新的权限。

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind improvement
/area core
/milestone 2.0

#### What this PR does / why we need it:
补充角色模板
#### Which issue(s) this PR fixes:

Fixes #2342 https://github.com/halo-dev/halo/issues/2391

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
