### PR TITLE
Adapt HTML5 history mode of console in non-proxy mode

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind bug
/area core

#### What this PR does / why we need it:

This PR adapts HTML5 history mode of console in non-proxy mode. In PR <https://github.com/halo-dev/halo/pull/4005>, history mode of console has changed from hash mode into HTML5 mode, so that we cannot access console project when refreshing pages.

#### Special notes for your reviewer:

1. Build console project by executing command `make -C console build`
1. Change value of property `halo.console.proxy.enabled` into `false`.
2. Start Halo and check console pages.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ruibaby** [comment]
@JohnNiang 有单元测试未通过。

**Comment by JohnNiang** [comment]
> @JohnNiang 有单元测试未通过。

The error has been fixed by <https://github.com/halo-dev/halo/pull/4018/commits/7d216230d0d268a1cc423105c2cd073ec7127254>.

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/approve

**Pull request merged**
