### PR TITLE
perf: refine display name of system default role

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

为系统初始化的角色添加显示名称

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3257

#### Screenshots:

image

#### Special notes for your reviewer:

see 

#### Does this PR introduce a user-facing change?

```release-note
为系统初始化的角色添加显示名称
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
It works very well.
/approve
image

**Comment by JohnNiang** [comment]
有一个问题可能需要注意一下，搜索功能可能需要适配一下。

image

**Pull request merged**
