### PR TITLE
Refactor CICD for Halo next

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind optimization
/area core
/milestone 2.0

#### What this PR does / why we need it:

1. Build docker image for halo next at every push into next branch.
3. Remove unused workflow manifests.
4. Refactor Dockerfile to adapt for halo next.
5. Make checkstyle check and test separate.

The last effect when pushing into next branch:

image

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve

**Comment by JohnNiang** [comment]
/hold
I'm trying to refactor the reusable workflow in [separate repository](https://github.com/halo-sigs/actions).

**Comment by JohnNiang** [comment]
/close
I will reopen this PR until I test them enough.

**Pull request closed without merging**
