### PR TITLE
Refine docker-run command in README.md

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

- Use arguments instead of environments.
- Change Docker image halo:2.0 into halo:2.1

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

文档也需要更改：https://github.com/halo-dev/docs/issues/163

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
