### PR TITLE
Add property halo.use-absolute-permalink to control permalink generation

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind improvement
/kind api-change
/area core
/milestone 2.5.x

#### What this PR does / why we need it:

Add property `halo.use-absolute-permalink`(default is `false`) to control permalink generation. Leave `halo.external-url` as `null` by default.

Meanwhile, I enhanced `ExternalUrlSupplier#getURL` to get URL from not only properties but only http request.

#### How to use it?

```yaml
halo:
  use-absolute-permalink: false
```

Or:

```yaml
halo:
  external-url: https://halo.run/
  use-absolute-permalink: false
```

Or:

```yaml
halo:
  external-url: https://halo.run/
  use-absolute-permalink: true
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3762

#### Does this PR introduce a user-facing change?

```release-note
新增是否生成相对地址的配置
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
image

配置了 `halo.external-url` 的情况下，`/actuator/globalinfo` 的 externalUrl 变成了 `/`

**Comment by guqing** [comment]
check 没过

**Comment by JohnNiang** [comment]
> check 没过

Done. Please check the [commit](https://github.com/halo-dev/halo/pull/3772/commits/d24de0a223c1d8bbad313d6a1184616cef8bbb40).

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
