### PR TITLE
Improve the quality of full-text searching result

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind improvement
/area core

#### What this PR does / why we need it:

This PR uses QueryParser to build Query instead of FuzzyQuery to improve the searching result quality.

image

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3234

#### Does this PR introduce a user-facing change?

```release-note
优化搜索查询结果
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
