### PR TITLE
Provide an endpoint to install plugin using Jar file

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:

Provide an endpoint to install plugin using Jar file.

#### Special notes for your reviewer:

Currently, you could login and open the swagger ui to test against this feature.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
/hold
Until we test this feature enough manually.

**Review by guqing — COMMENTED** [review]
/approve

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
