### PR TITLE
feat: archives in descending order by month

### LINKED ISSUE #2958: 归档页面数据，未按月份倒序
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

_No response_

### 发生了什么？

访问 /archives 地址，目前月份数据升序返回。此处建议月份降序返回。

因为年份是降序，月份升序，月份里的文章是降序。有点错乱。同时如果月份数据降序，对于主题制作时间轴等效果更加友好。

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by liaocp666**
#### What type of PR is this?
/kind improvement

#### What this PR does / why we need it:

优化归档页面数据排序，按月份降序

#### Which issue(s) this PR fixes:

Fixes #2958 

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo

#### Does this PR introduce a user-facing change?

```release-note
归档数据按月降序
```

### CODE REVIEW

**Comment by ruibaby** [comment]
@liaocp666 感谢你的贡献，在 Review 前需要先处理一下格式的问题 https://github.com/halo-dev/halo/actions/runs/3701412755/jobs/6271059361

**Comment by liaocp666** [comment]
@ruibaby 已处理

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/approve

符合预期。

image

**Comment by ruibaby** [comment]
感谢 @liaocp666 的发现和贡献。

**Pull request merged**
