### PR TITLE
refactor: improve part of the post operation logic using the patch api

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/area ui
/kind improvement
/milestone 2.19.x

#### What this PR does / why we need it:

使用 patch 接口重构文章的恢复、可见性修改等逻辑。

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

测试文章删除、恢复、可见性修改功能是否符合预期。

#### Does this PR introduce a user-facing change?

```release-note
使用 patch 接口重构文章的恢复、可见性修改等逻辑。
```

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
这里是否需要适配文章管理角色模板。

**Review by guqing — APPROVED** [review]
/approve
works very well

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
