### PR TITLE
fix: incorrect number of comments

### PR DESCRIPTION
**Pull request by longjuan**
#### What type of PR is this?
/kind bug
/area core

#### What this PR does / why we need it:
Fixed incorrect number of comments after comment deletion.
#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3287

#### Special notes for your reviewer:
为一篇文章添加多个评论，期望评论数量正确。
删除评论，期望评论数量正常减少。
删除全部评论，期望评论数量归零。
#### Does this PR introduce a user-facing change?

```release-note
修复删除评论后Console端文章和单页评论数量不正确
```

### CODE REVIEW

**Comment by longjuan** [comment]
我觉得`updateCommentCounter`方法可以改为只更新当前评论subjectRef的Counter

**Comment by guqing** [comment]
> 我觉得`updateCommentCounter`方法可以改为只更新当前评论subjectRef的Counter

确实可以，之前不是直接更新的数据库在内存中同步的无法加锁，后面重构过直接沿用了逻辑。

**Review by JohnNiang — COMMENTED** [review]
It works very well.

/lgtm

**Review by ruibaby — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
