### PR TITLE
refactor: the principle name and claims of the personal access token are set as the creators

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind improvement
/area core
/milestone 2.0

#### What this PR does / why we need it:
个人令牌绑定到具体创建者即如果用户 zhangsan 创建了一个 Personal Access Token ，则使用个人令牌认证时主体信息为 zhangsang 的用户名及扩展属性

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by JohnNiang** [comment]
/hold
Recently, I'm refactoring the Personal Access Token mechanism, so I hold this PR.

**Comment by JohnNiang** [comment]
I'm going to close this PR in favour of <https://github.com/halo-dev/halo/pull/2417>.
/close

**Pull request closed without merging**
