### PR TITLE
Fix invalid attachment role templates

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind bug
/area core
/milestone 2.1.x

#### What this PR does / why we need it:

- Add missing resources `"policies", "policytemplates", "groups"` in policy rules in attachment role templates.
- Correct `nonResourceURLs` and `verbs`

See https://github.com/halo-dev/halo/issues/3007 for more.

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3007

#### Special notes for your reviewer:

Steps to test:

1. Start Halo and login with `admin`
2. Create a Role with `Attachment Manage` permission only
3. Create an user and assign the role to the user
4. Set password for the user
5. Log out current user and log in as the user created just now
6. Try to do various operations in attachment tab
    - Create and list policy
    - Create and list group
    - Upload and list attachments

#### Does this PR introduce a user-facing change?

```release-note
修复附件权限定义的错误
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve

**Comment by ruibaby** [comment]
因为目前存储策略模板的表单配置是放在 Setting 模型，如果不勾选 Setting 的访问权限，也没有办法创建新的存储策略。

image

**Comment by JohnNiang** [comment]
/hold

See https://github.com/halo-dev/halo/pull/3024#issuecomment-1361561608 for more.

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
