### PR TITLE
Add role template for managing cache

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/area core
/milestone 2.7.x

#### What this PR does / why we need it:

Add role template for managing cache. Anyone with role `role-template-manage-cache` can see the `Refresh Page Cache` button.

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/4143

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @ruibaby , please help me regenerate API client, because cache endpoint was changed by me just now.

**Comment by ruibaby** [comment]
> Hi @ruibaby , please help me regenerate API client, because cache endpoint was changed by me just now.

Done

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — APPROVED** [review]
/approve

**Pull request merged**
