### PR TITLE
Upgrade to Spring Boot 3.4.0-M3

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind cleanup
/area core
/milestone 2.20.x

#### What this PR does / why we need it:

This PR upgrades to [Spring Boot 3.4.0-M3](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0-M3).

1. Fix the compilation error of OptimalPropertyAccess because the class has been privated in [this commit](https://github.com/spring-projects/spring-framework/commit/b4315940212b8e955215ffe09bafde228daa6eac).
2. Fix exception `org.mockito.exceptions.misusing.UnnecessaryStubbingException` for some unit tests after upgrading.
3. Replace deprecated annotations `@MockBean` and `@SpyBean` with `@MockitoBean` and `@MockitoSpyBean` respectively.

#### Does this PR introduce a user-facing change?

```release-note
升级 Spring Boot 至 3.4.0-M3
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Wait for https://github.com/halo-dev/halo/pull/6686 to be merged.

**Comment by guqing** [comment]
编译没过 需要修复一下

**Comment by JohnNiang** [comment]
> 编译没过 需要修复一下

编译错误和单元测试错误已经修复。

**Review by guqing — APPROVED** [review]
/lgtm

**Pull request merged**
