### PR TITLE
docs: fix command of docker run

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

修复 Docker 快速运行的 `halo.security.initializer.superadminusername` 参数。

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
My bad.

/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
> My bad.
> 
> 
> 
> /approve

Review 不力🤓

**Pull request merged**
