### PR TITLE
Upgrade Spring Boot to 3.0.0-M4

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind flake
/area core
/milestone 2.0

#### What this PR does / why we need it:

Upgrade Spring Boot to 3.0.0-M4. Please see <https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0-M4>.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
