### PR TITLE
refactor: comments are converted to publish before sending reply email

### LINKED ISSUE #2246: 评论邮件发送时机
### 你当前使用的版本

_No response_

### 描述一下此特性

目前当新访客给之前访客留的评论追评时，将会直接发送邮件给被追评的访客，即使已开启评论审核，那么就导致已留言的访客有被疯狂轰炸的风险

建议在站长审核通过后再发送邮件给已留言的访客，给站长留言不用改，还是即时通知

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by AirboZH**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
reply comments的评论审核通过时创建回复事件
添加了回复邮件发送的条件：当评论由管理员发布后回复邮件

#### Which issue(s) this PR fixes:

Fixes #2246

#### Special notes for your reviewer:

null

#### Does this PR introduce a user-facing change?

```release-note
修复未审核评论回复会发送邮件提醒的问题
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/approve

**Comment by ruibaby** [comment]
/retitle refactor: comments are converted to publish before sending reply email

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
