### PR TITLE
feat: open actuator logfile endpoint for prod

### LINKED ISSUE #3188: Request to be able to view and download logs from console
### Your current Halo version

2.2.0-SNAPSHOT

### Describe this feature

We can use actuator endpoint `logfile` to fetch logs and display them at console. After that, administrators are freed from loggin into the server and downloading log files for viewing.

### Additional information

See 
- <https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#logfile> 
- <https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#logfile.retrieving-part>

for more.

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #3188 

#### Special notes for your reviewer:
测试方式：
1. 使用 prod 模式启动项目，使用超级管理员登陆
2. 访问 /actuator/logfile 查看是否有日志显示。

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by LIlGG** [comment]
Fixes #3188

**Review by JohnNiang — APPROVED** [review]
It works very well.

image

/approve

**Review by ruibaby — APPROVED** [review]
/lgtm

**Pull request merged**
