### PR TITLE
feat: use storybook to refactor components library docs

### LINKED ISSUE #4117: 使用 Storybook 重构 Console 组件库的文档
### 你当前使用的版本

2.6.2

### 描述一下此特性

如题，建议使用 [Storybook](https://storybook.js.org/) 完善 Console 的组件库文档和 Demo 演示，并在开发者文档中公开。

/kind feature
/area console
/milestone 2.8.x

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by pillar-cat**
#### What type of PR is this?
/kind feature
/area console
/milestone 2.8.x

#### What this PR does / why we need it:
Console Components使用StoryBook代替Histories

#### Which issue(s) this PR fixes:

Fixes #4117 

#### Special notes for your reviewer:

1. 移动到 console/packages/components 目录。
2. pnpm storybook

#### Does this PR introduce a user-facing change?

```release-note
使用 Storybook 重构 `@halo-dev/components` 文档。
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @pillar-cat ，在 Review 之前需要先解决一下冲突。

**Review by ruibaby — COMMENTED** [review]
/lgtm

图片

**Review by ruibaby — COMMENTED** [review]
/approve

cc @halo-dev/sig-halo-console

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
