### PR TITLE
refactor: using index mechanisms to optimize comment queries

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind improvement
/area core
/milestone 2.14.x

#### What this PR does / why we need it:
使用索引机制优化评论数据查询以提高效率

how to test it?
- 测试 console 评论列表和筛选条件是否正确
- 测试主题端评论显示是否正确

#### Does this PR introduce a user-facing change?
```release-note
使用索引机制优化评论数据查询以提高效率
```

### CODE REVIEW

**Comment by ruibaby** [comment]
> /cc @ruibaby 需要重新修改一下评论列表的筛选条件和排序的字段

已修改。

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
