### PR TITLE
Fix the meta description with special characters causing the page to display abnormally

### LINKED ISSUE #4000: 文章内容导致页面显示异常
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

_No response_

#### 描述:

在编辑文章时, 如果用了 *附加信息* 中的文本发布文章, 整个 halo 下的文章中的代码块渲染会出现异常(用主题 Sakura 2.0.0 版本可以明显看出), 并且页面内容会出现异常

**所有异常均不止有一个页面会出现**

##### 代码渲染异常:

首先这是正常的代码渲染:

这是异常的渲染:

##### 页面异常:

见下图顶部:

#### 可能引起异常的句子:

具体引起异常的句子是下图第 9 行到 13 行:

如果删除这行就会恢复正常

#### 复现:

- halo 最新版
- 以 *附加信息* 中的文本发布文章

### 相关日志输出

_No response_

### 附加信息
这是引起异常的文本:

```
## Lambda 表达式:

### Lambda 语法:

使用 lambda 表达式的一般语法是:

> `(Parameters) -> { Body }`

"->" 分隔参数和 lambda 表达式主体

参数括在括号中, 与方法相同, 而 lambda 表达式主体是用大括号括起来的代码块

lambda 表达式主体可以有局部变量和语句

我们可以在 lambda 表达式主体中使用 `break`, `continue` 和 `return`, 也可以从 lambda 表达式主体中抛出异常

- lambda 表达式没有名称, 因为它表示匿名内部类

- lambda 表达式的返回类型由编译器推断

- lambda 表达式不能像方法一样有 `throws` 子句

- lambda 表达式不能是泛型, 而泛型在函数接口中定义
```

_No response_

### PR DESCRIPTION
**Pull request by Contour-D**
#### What type of PR is this?

/kind bug
/area core

#### What this PR does / why we need it:
Fix the problem that the meta description with special characters causes the page to display abnormally.
Use htmlEscape in org.springframework.web.util.HtmlUtils to escape the special characters contained in the original description.

see #4000 
#### Which issue(s) this PR fixes:

Fixes #4000

#### Does this PR introduce a user-facing change?

```release-note
修复 meta description 中含有特殊字符导致页面显示异常的问题
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
image

/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
