### PR TITLE
feat: add the clear format function to the default rich text editor

### LINKED ISSUE #5684: 为默认编辑器添加清除格式的功能
### 你当前使用的版本

_No response_

### 描述一下此特性

当往默认富文本编辑器中粘贴的某些带有格式的内容时，可能会出现格式并不符合要求。

并且目前想一键清除所有格式时，需要依次取消掉所有的格式。

基于上述要求，因此期望能够增加清除格式的功能。

/area editor
/kind feature
/milestone 2.15.x

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?

/kind feature
/area editor
/milestone 2.15.x

#### What this PR does / why we need it:

为默认富文本编辑器添加清除格式的功能。快捷键为 `Mod + \`。

#### How to test it?

输入文本，使用加粗、链接、斜体等 mark 相关功能，之后使用清除格式，查看格式是否被清除。

#### Which issue(s) this PR fixes:

Fixes #5684 

#### Does this PR introduce a user-facing change?
```release-note
为默认富文本编辑器添加清除格式的功能。
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/approve

**Pull request merged**
