### PR TITLE
feat: update default comment sorter

### LINKED ISSUE #3138: 需要优化 Console 端评论的默认排序规则
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.run

### 发生了什么？

目前在 Console 端的评论管理的默认排序为最后回复时间，意思就是如果某一条评论新增了回复，那么会放在最前面以提示管理者有新的回复，这是符合预期的。但是目前无法将最新创建的评论放在最前面，导致无法及时知道有新的评论。

默认情况下：

image

手动排序：

image

/kind improvement
/area core
/milestone 2.2.x

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by vayci**
#### What type of PR is this?

/kind feature
/kind improvement

#### What this PR does / why we need it:

Update comments default sorter for console

#### Which issue(s) this PR fixes:

Fixes #3138 

#### Does this PR introduce a user-facing change?

```release-note
修改评论列表默认排序规则：依据最后回复时间及评论创建时间进行排序
```

### CODE REVIEW

**Comment by guqing** [comment]
code style 需要处理一下

**Comment by vayci** [comment]
> code style 需要处理一下， CI 没有过

好的

**Review by ruibaby — COMMENTED** [review]
/lgtm

image

**Comment by vayci** [comment]
@ruibaby merge代码导致review标签失效，麻烦再看一下

**Review by ruibaby — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
