### PR TITLE
Refactor reconcilers registration

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind cleanup
/kind improvement
/area core
/milestone 2.0.0

#### What this PR does / why we need it:

This PR mainly refactors registration of reconcilers to register reconciler more convinient. After that, it is possible to reigster and start reconciler in plugin.

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2305

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve

**Comment by JohnNiang** [comment]
> /remove-approve /hold until #2759 merged

IMO, the problem https://github.com/halo-dev/halo/issues/2758 does not prevent the current PR from being merged.

/unhold

**Review by guqing — COMMENTED** [review]
/approve

**Review by ruibaby — APPROVED** [review]
/lgtm

**Pull request merged**
