### PR TITLE
Simplify MenuItem with targetRef instead of multi refs

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind improvement
/kind api-change
/area core
/milestone 2.0.x

#### What this PR does / why we need it:

Two things this PR does:

1. **Simplify MenuItem with targetRef instead of multi refs**
2. Organize extensions with group `content.halo.run` into content folder

> **Warning** The first thing has some break changes about structure of MenuItem, please @halo-dev/sig-halo-console be aware of that.

Before:

```java
        @Schema(description = "Category reference.")
        private Ref categoryRef;

        @Schema(description = "Tag reference.")
        private Ref tagRef;

        @Schema(description = "Post reference.")
        private Ref postRef;

        @Schema(description = "SinglePage reference.")
        private Ref singlePageRef;
```

After:

```java
        @Schema(description = "Target reference. Like Category, Tag, Post or SinglePage")
        private Ref targetRef;
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2739

#### Special notes for your reviewer:

Because this PR contains break changes, we cannot test it in console directly.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ruibaby** [comment]
Got it!

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by ruibaby — COMMENTED** [review]
/lgtm

/cc @halo-dev/sig-halo

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
