### PR TITLE
chore: bump vite version to 6.0.3

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/area ui
/kind improvement

#### What this PR does / why we need it:

Bump vite version to [6](https://vite.dev/guide/migration.html)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by guqing** [comment]
build 失败了

**Comment by JohnNiang** [comment]
Hi @ruibaby, there has conflicts that must be resolved before merging.

**Comment by ruibaby** [comment]
> Hi @ruibaby, there has conflicts that must be resolved before merging.

Fixed

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
