### PR TITLE
refactor: remove authorization filter and replace it with the RequestInfoAuthorizationManager

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
使用 AuthorizationManager 实现重构 之前的 AuthorizationFilter，避免了总是会经过它而无法跳过白名单url

#### How to test it
1. 访问白名单资源
```shell
$ curl http://localhost:8090/static/js/test.js
# 结果：console.log('hello world!')
```

2. 测试访问需要授权资源，首先登录
```
curl -X POST http://localhost:8090/api/v1/oauth2/token -H "Content-Type: application/x-www-form-urlencoded" -d 'username=user&password=123456&grant_type=password'
```
以上用户的规则如下：
```java
new PolicyRule.Builder().apiGroups("").resources("posts").verbs("list", "get")
    .build()
new PolicyRule.Builder().apiGroups("").resources("categories").verbs("*")
    .build()
new PolicyRule.Builder().nonResourceURLs("/healthy").verbs("get", "post", "head")
    .build()
```

访问 posts 资源
```shell
$ curl http://localhost:8090/api/v1/posts -H "Authorization: Bearer your-access-token"
# 结果：list posts.

$ curl http://localhost:8090/api/v1/posts/some-name -H "Authorization: Bearer your-access-token"
# 结果：Gets a post with the name: some-name

$ curl http://localhost:8090/api/v1/tags -H "Authorization: Bearer your-access-token"
# 结果：
{
    "timestamp": "2022-05-10 08:49:39",
    "status": 403,
    "error": "Forbidden",
    "message": "Forbidden",
    "path": "/api/v1/tags"
}

$ curl http://localhost:8090/healthy -H "Authorization: Bearer your-access-token"
# 结果：I am very healthy.

$ curl -X DELETE http://localhost:8090/healthy
# 结果：Unauthorized

$ curl -X DELETE http://localhost:8090/healthy -H "Authorization: Bearer your-access-token"
# 结果：HTTP ERROR 403 Forbidden
```
白名单
```shell
curl http://localhost:8090/static/js/test.js
```
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/cc @halo-dev/sig-halo
/milestone 2.0
/area core

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by JohnNiang — CHANGES_REQUESTED** [review]
可能需要一个测试来保证配置了 permitAll 是生效的

```java
.antMatchers("/xxx").permitAll()
```

**Comment by guqing** [comment]
> 可能需要一个测试来保证配置了 permitAll 是生效的
> 
> ```java
> .antMatchers("/xxx").permitAll()
> ```
已有测试，提供了两种
1. 手动测试部分
https://github.com/halo-dev/halo/pull/2081/files#diff-5f6746c027049af0723c48feea24848f655b82a600d40d5b43f837c33b1a596dR86
https://github.com/halo-dev/halo/pull/2081/files#diff-75b15b802abd252ac4d3d5fabc67aced0d52aee9ab2c17f171a023027bff3444R25-R28

2. 单元测试部分
https://github.com/halo-dev/halo/pull/2081/files#diff-75b15b802abd252ac4d3d5fabc67aced0d52aee9ab2c17f171a023027bff3444R25-R28
https://github.com/halo-dev/halo/pull/2081/files#diff-75b15b802abd252ac4d3d5fabc67aced0d52aee9ab2c17f171a023027bff3444R25-R28
https://github.com/halo-dev/halo/pull/2081/files#diff-2c501841147cd2a4aa65cccc61d978161bcee02a3b832a08d8ebb239cc75b34eR88

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
