### PR TITLE
Include posts that under the subcategories when getting posts b…

### PR DESCRIPTION
**Pull request by guqing**
### What this PR does?
- 根据分类获取文章时包含该分类的所有子分类的文章
- 重构获取包含文章数量的分类列表功能
- 影响了当前代码逻辑的代码顺手重构之

### Why we need it?
#1550

### How to test it?
主要测试后台和前台的文章列表和分类列表
对于文章列表，点击分类筛选文章时查看是否包含子分类下的文章且关注分类的文章数量是否正确
示例：
有如下分类及文章关系
```
—— 分类1
——｜文章1，文章2，文章3
———— 分类1-1
————｜文章4，文章5
```
-  根据`分类1`筛选文章时，应该展示（文章1，文章2，文章3，文章4，文章5）且分类1的文章数量为 5
- 根据`分类1-1`筛选文章时,应该展示（文章4，文章5）且`分类1-1`的文章数量为 2

查看分类菜单下的分类列表文章数量是否正确 同文章列表

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
LGTM

**Comment by hugeleaf** [comment]
@JohnNiang  Is this commit released?  Is there a release planned?

**Comment by JohnNiang** [comment]
> @ruibaby @JohnNiang Is this commit released? Is there a release planned?

Please refer to https://github.com/halo-dev/halo/commit/9ddd74b74bf6513c88874af08290b302a5237a43.

image

**Comment by hugeleaf** [comment]
> > @ruibaby @JohnNiang Is this commit released? Is there a release planned?
> 
> Please refer to [9ddd74b](https://github.com/halo-dev/halo/commit/9ddd74b74bf6513c88874af08290b302a5237a43).
> 
> image

In page variable of category.ftl, there are still no articles in the subcategory list into posts.content.

**Pull request merged**
