### PR TITLE
chore: upgrade spring boot to 2.5.12

### PR DESCRIPTION
**Pull request by guqing**
### What this PR does?
升级 springboot 到 2.5.12
> https://docs.spring.io/spring-boot/docs/2.5.12/reference/html/

/kind dependencies
/cc @halo-dev/sig-halo

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/lgtm
/approve

**Comment by guqing** [comment]
image

**Pull request merged**
