### PR TITLE
fix: the image tag might be wrong when it is not a pr

### PR DESCRIPTION
**Pull request by LinuxSuRen**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
https://github.com/halo-dev/halo/pull/4892 caused a bug. See https://github.com/halo-dev/halo/actions/runs/6968131488/job/18961558573

image

I have tested it in another PR https://github.com/LinuxSuRen/halo/pull/2. But the main branch building is failed due to some reasons. See also https://github.com/LinuxSuRen/halo/actions/runs/6968762257/job/18963304428

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
/approve

Meanwhile, I found that we could obtain some useful environments genrerated from previous step, as shown below, which would be better if we could use them. Of course, this will not prevent the current PR from merging.

```yaml
env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    DOCKER_METADATA_OUTPUT_VERSION: pr-4903
    DOCKER_METADATA_OUTPUT_TAGS: ghcr.io/halo-dev/halo-dev:pr-4903
  ghcr.io/halo-dev/halo-dev:sha-0ba4415
    DOCKER_METADATA_OUTPUT_LABELS: org.opencontainers.image.created=2023-[11](https://github.com/halo-dev/halo/actions/runs/6968839600/job/18964740628?pr=4903#step:5:11)-23T11:46:54.[14](https://github.com/halo-dev/halo/actions/runs/6968839600/job/18964740628?pr=4903#step:5:14)9Z
  org.opencontainers.image.description=强大易用的开源建站工具。
  org.opencontainers.image.licenses=GPL-3.0
  org.opencontainers.image.revision=0ba44[15](https://github.com/halo-dev/halo/actions/runs/6968839600/job/18964740628?pr=4903#step:5:15)f5[19](https://github.com/halo-dev/halo/actions/runs/6968839600/job/18964740628?pr=4903#step:5:19)3857415224bf692c5a8aa143bee5b
  org.opencontainers.image.source=https://github.com/halo-dev/halo
  org.opencontainers.image.title=halo
  org.opencontainers.image.url=https://github.com/halo-dev/halo
  org.opencontainers.image.version=pr-4903
    DOCKER_METADATA_OUTPUT_JSON: {"tags":["ghcr.io/halo-dev/halo-dev:pr-4903","ghcr.io/halo-dev/halo-dev:sha-0ba4415"],"labels":{"org.opencontainers.image.created":"[20](https://github.com/halo-dev/halo/actions/runs/6968839600/job/18964740628?pr=4903#step:5:20)23-11-23T11:46:54.149Z","org.opencontainers.image.description":"强大易用的开源建站工具。","org.opencontainers.image.licenses":"GPL-3.0","org.opencontainers.image.revision":"0ba4415f5193857415224bf692c5a8aa143bee5b","org.opencontainers.image.source":"https://github.com/halo-dev/halo","org.opencontainers.image.title":"halo","org.opencontainers.image.url":"https://github.com/halo-dev/halo","org.opencontainers.image.version":"pr-4903"}}
    DOCKER_METADATA_OUTPUT_BAKE_FILE: /tmp/docker-actions-toolkit-9Yfi9R/docker-metadata-action-bake.json
```

**Comment by JohnNiang** [comment]
I'm going to merge this PR as soon as possible to prevent GitHub checks at main branch from failing.

/lgtm

**Comment by LinuxSuRen** [comment]
`DOCKER_METADATA_OUTPUT_VERSION` would be a good choice. I can update it later. Those test cases are not enough.

**Comment by JohnNiang** [comment]
> `DOCKER_METADATA_OUTPUT_VERSION` would be a good choice. I can update it later. Those test cases are not enough.

The choice won't prevent the current PR from merging. I will manually merge this PR immediately because the checks always fail at main branch.

**Pull request merged**
