### PR TITLE
refactor: optimizing regex pettern for html meta matching

### LINKED ISSUE #4234: 重复 HTML Meta 标签没有被完全处理
### Your current Halo version

2.7.0

### Describe this feature

PR https://github.com/halo-dev/halo/pull/4069 对 HTML Meta 重复的标签进行了处理，但是对有些标签无法去除重复
1. name 属性和 content 属性位置颠倒时无法去除
```
            
<meta content="全局 Head description" name="description" />
            
<style>
  .moment .momemt-content pre.notranslate {
    background: #f3f3f3;
    color: #444;
  }
</style>
```
2. 带了自结束标记的 meta 无法去除重复
```
<meta name="description" content="Hi ther" />
```
属于正则表达式有问题，需要优化一下

### Additional information

/kind improvement
/area core
/milestone 2.8.x
/assign

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind improvement
/area core
/milestone 2.8.x

#### What this PR does / why we need it:
优化去除 Html Meta 重复标签的正则表达式

see #4234 for more details.

#### Which issue(s) this PR fixes:

Fixes #4234

#### Does this PR introduce a user-facing change?

```release-note
优化去除 Html Meta 重复标签的正则表达式
```

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
似乎缺少对应的测试用例。

**Comment by guqing** [comment]
> 似乎缺少对应的测试用例。

添加了对应正则的测试用例

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
