### PR TITLE
Fix AttachmentReconciler repeated execution

### LINKED ISSUE #3746: AttachmentHandler 的 delete 会多调用一次
### 是什么版本出现了此问题？

2.4

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

_No response_

### 发生了什么？

首先我不清楚这是不是一个bug，AttachmentHandler 的 delete 方法会多调用一次，如果我删除一个附件，会调用两次，如果删除2个文件，就会调用3次，最后一次删除会重复再删一次。

### 相关日志输出

```shell
2023-04-13T00:40:09.111+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] at 2023-04-12T16:40:09.111223200Z
2023-04-13T00:40:09.111+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.MenuItemReconciler-worker-1 >>> Reconciling request Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] at 2023-04-12T16:40:09.111223200Z
2023-04-13T00:40:09.263+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.MenuItemReconciler-worker-1 >>> Reconciled request: Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] with result: Result[reEnqueue=true, retryAfter=PT1M], usage: 152
2023-04-13T00:40:09.263+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] after PT1M
2023-04-13T00:40:09.263+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] after PT1M
2023-04-13T00:40:10.057+08:00 DEBUG 25144 --- [netty-thread-24] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] immediately
2023-04-13T00:40:10.057+08:00 DEBUG 25144 --- [netty-thread-24] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] after PT0.5S
2023-04-13T00:40:10.057+08:00 DEBUG 25144 --- [netty-thread-24] r.h.a.extension.controller.DefaultQueue  : Added request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] after PT0.5S
2023-04-13T00:40:10.057+08:00 DEBUG 25144 --- [netty-thread-24] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] immediately
2023-04-13T00:40:10.057+08:00 DEBUG 25144 --- [netty-thread-24] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] after PT0.005S
2023-04-13T00:40:10.057+08:00 DEBUG 25144 --- [netty-thread-24] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] after PT0.005S
2023-04-13T00:40:10.073+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] at 2023-04-12T16:40:10.073985600Z
2023-04-13T00:40:10.073+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciling request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] at 2023-04-12T16:40:10.073985600Z
2023-04-13T00:40:10.190+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.app.plugin.SpringExtensionFactory    :   Extension class ' run.halo.oss.GitHubAttachmentHandler' belongs to halo-plugin 'PluginGitHubOSS' and will be autowired by using its application context.
2023-04-13T00:40:10.191+08:00 DEBUG 25144 --- [tReconciler-t-1] run.halo.oss.GitHubAttachmentHandler     : 开始删除文件:{"spec":{"displayName":"59506456-50a7-4d57-a34b-ebc60ad99ad3.png","policyName":"default-policy","ownerName":"admin","mediaType":"image/png","size":91396},"status":{"permalink":"/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png"},"apiVersion":"storage.halo.run/v1alpha1","kind":"Attachment","metadata":{"name":"16c6d2eb-2b78-4043-a346-437ed577a9f5","annotations":{"storage.halo.run/uri":"/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png","storage.halo.run/local-relative-path":"upload\\59506456-50a7-4d57-a34b-ebc60ad99ad3.png"},"version":3,"creationTimestamp":1681317471683,"deletionTimestamp":1681317609979,"finalizers":["attachment-manager"]}}
2023-04-13T00:40:10.191+08:00 DEBUG 25144 --- [tReconciler-t-1] run.halo.oss.GitHubAttachmentHandler     : Github Oss 模板元数据配置: :{"name":"default-policy","version":0,"creationTimestamp":1681148627425}
2023-04-13T00:40:10.192+08:00  INFO 25144 --- [undedElastic-17] h.a.c.e.a.e.LocalAttachmentUploadHandler : Trying to delete 16c6d2eb-2b78-4043-a346-437ed577a9f5 from local
2023-04-13T00:40:10.192+08:00  INFO 25144 --- [undedElastic-17] h.a.c.e.a.e.LocalAttachmentUploadHandler : C:\Users\29413\halo2-dev\attachments\upload\59506456-50a7-4d57-a34b-ebc60ad99ad3.png is being deleted
2023-04-13T00:40:10.192+08:00  INFO 25144 --- [undedElastic-17] h.a.c.e.a.e.LocalAttachmentUploadHandler : Attachment(super=AbstractExtension(apiVersion=storage.halo.run/v1alpha1, kind=Attachment, metadata=Metadata(name=16c6d2eb-2b78-4043-a346-437ed577a9f5, generateName=null, labels=null, annotations={storage.halo.run/uri=/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png, storage.halo.run/local-relative-path=upload\59506456-50a7-4d57-a34b-ebc60ad99ad3.png}, version=3, creationTimestamp=2023-04-12T16:37:51.683979300Z, deletionTimestamp=2023-04-12T16:40:09.979823100Z, finalizers=[attachment-manager])), spec=Attachment.AttachmentSpec(displayName=59506456-50a7-4d57-a34b-ebc60ad99ad3.png, groupName=null, policyName=default-policy, ownerName=admin, mediaType=image/png, size=91396, tags=null), status=Attachment.AttachmentStatus(permalink=/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png)) was deleted successfully
2023-04-13T00:40:10.418+08:00 DEBUG 25144 --- [-netty-thread-6] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] immediately
2023-04-13T00:40:10.418+08:00 DEBUG 25144 --- [-netty-thread-6] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] after PT0.5S
2023-04-13T00:40:10.418+08:00 DEBUG 25144 --- [-netty-thread-6] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] immediately
2023-04-13T00:40:10.418+08:00 DEBUG 25144 --- [-netty-thread-6] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] after PT0.005S
2023-04-13T00:40:10.418+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciled request: Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] with result: null, usage: 344
2023-04-13T00:40:10.432+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] at 2023-04-12T16:40:10.432831Z
2023-04-13T00:40:10.432+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciling request Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] at 2023-04-12T16:40:10.432831Z
2023-04-13T00:40:10.545+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.app.plugin.SpringExtensionFactory    :   Extension class ' run.halo.oss.GitHubAttachmentHandler' belongs to halo-plugin 'PluginGitHubOSS' and will be autowired by using its application context.
2023-04-13T00:40:10.546+08:00 DEBUG 25144 --- [tReconciler-t-1] run.halo.oss.GitHubAttachmentHandler     : 开始删除文件:{"spec":{"displayName":"59506456-50a7-4d57-a34b-ebc60ad99ad3.png","policyName":"default-policy","ownerName":"admin","mediaType":"image/png","size":91396},"status":{"permalink":"/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png"},"apiVersion":"storage.halo.run/v1alpha1","kind":"Attachment","metadata":{"name":"16c6d2eb-2b78-4043-a346-437ed577a9f5","annotations":{"storage.halo.run/uri":"/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png","storage.halo.run/local-relative-path":"upload\\59506456-50a7-4d57-a34b-ebc60ad99ad3.png"},"version":4,"creationTimestamp":1681317471683,"deletionTimestamp":1681317609979,"finalizers":[]}}
2023-04-13T00:40:10.546+08:00 DEBUG 25144 --- [tReconciler-t-1] run.halo.oss.GitHubAttachmentHandler     : Github Oss 模板元数据配置: :{"name":"default-policy","version":0,"creationTimestamp":1681148627425}
2023-04-13T00:40:10.546+08:00  INFO 25144 --- [undedElastic-16] h.a.c.e.a.e.LocalAttachmentUploadHandler : Trying to delete 16c6d2eb-2b78-4043-a346-437ed577a9f5 from local
2023-04-13T00:40:10.546+08:00  INFO 25144 --- [undedElastic-16] h.a.c.e.a.e.LocalAttachmentUploadHandler : C:\Users\29413\halo2-dev\attachments\upload\59506456-50a7-4d57-a34b-ebc60ad99ad3.png is being deleted
2023-04-13T00:40:10.546+08:00  INFO 25144 --- [undedElastic-16] h.a.c.e.a.e.LocalAttachmentUploadHandler : Attachment(super=AbstractExtension(apiVersion=storage.halo.run/v1alpha1, kind=Attachment, metadata=Metadata(name=16c6d2eb-2b78-4043-a346-437ed577a9f5, generateName=null, labels=null, annotations={storage.halo.run/uri=/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png, storage.halo.run/local-relative-path=upload\59506456-50a7-4d57-a34b-ebc60ad99ad3.png}, version=4, creationTimestamp=2023-04-12T16:37:51.683979300Z, deletionTimestamp=2023-04-12T16:40:09.979823100Z, finalizers=[])), spec=Attachment.AttachmentSpec(displayName=59506456-50a7-4d57-a34b-ebc60ad99ad3.png, groupName=null, policyName=default-policy, ownerName=admin, mediaType=image/png, size=91396, tags=null), status=Attachment.AttachmentStatus(permalink=/upload/59506456-50a7-4d57-a34b-ebc60ad99ad3.png)) was not exist
2023-04-13T00:40:10.558+08:00 DEBUG 25144 --- [-controller-t-5] r.h.a.extension.controller.DefaultQueue  : Take request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] at 2023-04-12T16:40:10.558438400Z
2023-04-13T00:40:10.558+08:00 DEBUG 25144 --- [-controller-t-5] r.h.a.e.controller.DefaultController     : garbage-collector-controller-worker-5 >>> Reconciling request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] at 2023-04-12T16:40:10.558438400Z
2023-04-13T00:40:10.558+08:00 DEBUG 25144 --- [-controller-t-5] run.halo.app.extension.gc.GcReconciler   : Extension GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] is being deleted
2023-04-13T00:40:10.582+08:00 DEBUG 25144 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciled request: Request[name=16c6d2eb-2b78-4043-a346-437ed577a9f5] with result: null, usage: 150
2023-04-13T00:40:10.711+08:00 DEBUG 25144 --- [-controller-t-5] run.halo.app.extension.gc.GcReconciler   : Extension GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] was deleted
2023-04-13T00:40:10.712+08:00 DEBUG 25144 --- [-controller-t-5] r.h.a.e.controller.DefaultController     : garbage-collector-controller-worker-5 >>> Reconciled request: GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=16c6d2eb-2b78-4043-a346-437ed577a9f5] with result: null, usage: 154
2023-04-13T00:40:12.496+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=c4c814d1-0c2c-456b-8c96-4864965fee94] at 2023-04-12T16:40:12.496324500Z
2023-04-13T00:40:12.496+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.MenuItemReconciler-worker-1 >>> Reconciling request Request[name=c4c814d1-0c2c-456b-8c96-4864965fee94] at 2023-04-12T16:40:12.496324500Z
2023-04-13T00:40:12.628+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.MenuItemReconciler-worker-1 >>> Reconciled request: Request[name=c4c814d1-0c2c-456b-8c96-4864965fee94] with result: Result[reEnqueue=true, retryAfter=PT1M], usage: 131
2023-04-13T00:40:12.628+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=c4c814d1-0c2c-456b-8c96-4864965fee94] after PT1M
2023-04-13T00:40:12.628+08:00 DEBUG 25144 --- [mReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=c4c814d1-0c2c-456b-8c96-4864965fee94] after PT1M
```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by Contour-D**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix AttachmentReconciler repeated execution.

#### Which issue(s) this PR fixes:

Fixes #3746

#### Special notes for your reviewer:
The reconile method in run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler will be executed repeatedly, uploading an attachment will be executed twice, because updating the finalizers property will be in onUpdate of run.halo.app.extension.controller.ExtensionWatcher Will request duplicate addition, I provide a fix for you to review
#### Does this PR introduce a user-facing change?

```release-note
修复 AttachmentReconciler 重复执行
```

### CODE REVIEW

**Comment by guqing** [comment]
@JohnNiang 对于只有 finalizers 的变更是否需要像 status 那样统一不 requeue

**Comment by guqing** [comment]
> 这里不建议像 status 那样处理。更改 finalizer 后需要触发 GC。

确实，应该是 delete 的调用有问题，或许应该写为:
```java
if (attachment.getMetadata().getDeletionTimestamp() != null) {
      removeFinalizer(attachment.getMetadata().getName());
      return;
  }

void removeFinalizer(String attachmentName) {
    client.fetch(Attachment.class, attachmentName).ifPresent(attachment -> {
        var finalizers = attachment.getMetadata().getFinalizers();
        if (finalizers != null && finalizers.remove(Constant.FINALIZER_NAME)) {
           // delete attachment
            attachmentService.delete(attachment).block();
            // then update it
            client.update(attachment);
        }
    });
}
```

**Comment by Contour-D** [comment]
好的，稍后我会按照 @guqing 提供的修改，麻烦你们了

**Review by JohnNiang — APPROVED** [review]
I confirm that it works very well.

````java
2023-06-10T10:04:22.685+08:00 DEBUG 75696 --- [ctor-http-nio-2] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] immediately
2023-06-10T10:04:22.685+08:00 DEBUG 75696 --- [ctor-http-nio-2] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] after PT0.5S
2023-06-10T10:04:22.685+08:00 DEBUG 75696 --- [ctor-http-nio-2] r.h.a.extension.controller.DefaultQueue  : Added request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] after PT0.5S
2023-06-10T10:04:22.685+08:00 DEBUG 75696 --- [ctor-http-nio-2] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] immediately
2023-06-10T10:04:22.685+08:00 DEBUG 75696 --- [ctor-http-nio-2] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] after PT0.005S
2023-06-10T10:04:22.685+08:00 DEBUG 75696 --- [ctor-http-nio-2] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] after PT0.005S
2023-06-10T10:04:22.691+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] at 2023-06-10T02:04:22.691808Z
2023-06-10T10:04:22.691+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciling request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] at 2023-06-10T02:04:22.691964Z
2023-06-10T10:04:22.695+08:00  INFO 75696 --- [oundedElastic-3] h.a.c.e.a.e.LocalAttachmentUploadHandler : Trying to delete cfe59be6-3833-4f6b-a840-a0c7705b266d from local
2023-06-10T10:04:22.696+08:00  INFO 75696 --- [oundedElastic-3] h.a.c.e.a.e.LocalAttachmentUploadHandler : /Users/johnniang/halo2-dev/attachments/upload/image_2023-06-09_16-16-17.png is being deleted
2023-06-10T10:04:22.696+08:00  INFO 75696 --- [oundedElastic-3] h.a.c.e.a.e.LocalAttachmentUploadHandler : Attachment(super=AbstractExtension(apiVersion=storage.halo.run/v1alpha1, kind=Attachment, metadata=Metadata(name=cfe59be6-3833-4f6b-a840-a0c7705b266d, generateName=null, labels=null, annotations={storage.halo.run/local-relative-path=upload/image_2023-06-09_16-16-17.png, storage.halo.run/uri=/upload/image_2023-06-09_16-16-17.png}, version=3, creationTimestamp=2023-06-10T02:04:13.039220Z, deletionTimestamp=2023-06-10T02:04:22.683379Z, finalizers=[attachment-manager])), spec=Attachment.AttachmentSpec(displayName=image_2023-06-09_16-16-17.png, groupName=null, policyName=default-policy, ownerName=admin, mediaType=image/png, size=155356, tags=null), status=Attachment.AttachmentStatus(permalink=/upload/image_2023-06-09_16-16-17.png)) was deleted successfully
2023-06-10T10:04:22.707+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] immediately
2023-06-10T10:04:22.707+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] after PT0.5S
2023-06-10T10:04:22.707+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] immediately
2023-06-10T10:04:22.707+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] after PT0.005S
2023-06-10T10:04:22.707+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciled request: Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] with result: null, usage: 15
2023-06-10T10:04:22.713+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] at 2023-06-10T02:04:22.713806Z
2023-06-10T10:04:22.714+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciling request Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] at 2023-06-10T02:04:22.714045Z
2023-06-10T10:04:22.714+08:00 DEBUG 75696 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler-worker-1 >>> Reconciled request: Request[name=cfe59be6-3833-4f6b-a840-a0c7705b266d] with result: null, usage: 0
2023-06-10T10:04:23.190+08:00 DEBUG 75696 --- [-controller-t-9] r.h.a.extension.controller.DefaultQueue  : Take request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] at 2023-06-10T02:04:23.190520Z
2023-06-10T10:04:23.190+08:00 DEBUG 75696 --- [-controller-t-9] r.h.a.e.controller.DefaultController     : garbage-collector-controller-worker-9 >>> Reconciling request GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] at 2023-06-10T02:04:23.190929Z
2023-06-10T10:04:23.191+08:00 DEBUG 75696 --- [-controller-t-9] run.halo.app.extension.gc.GcReconciler   : Extension GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] is being deleted
2023-06-10T10:04:23.198+08:00 DEBUG 75696 --- [-controller-t-9] run.halo.app.extension.gc.GcReconciler   : Extension GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] was deleted
2023-06-10T10:04:23.198+08:00 DEBUG 75696 --- [-controller-t-9] r.h.a.e.controller.DefaultController     : garbage-collector-controller-worker-9 >>> Reconciled request: GcRequest[gvk=storage.halo.run/v1alpha1/Attachment, name=cfe59be6-3833-4f6b-a840-a0c7705b266d] with result: null, usage: 7
````

/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
@Contour-D check 没有通过。

https://github.com/halo-dev/halo/actions/runs/5224394791/jobs/9432541327#step:5:1

**Pull request merged**
